### ISSUE TITLE
能否支持子级deck

### ISSUE THREAD

**Issue by terwer** [Clouder0/AnkiSiyuan#11]
![image](https://user-images.githubusercontent.com/3259282/205937713-5da7f2a5-7fdf-4d9d-9166-8bd5d36738df.png)
如图，父级并没有提取，而是当成两个毫不相干的牌组了。

期望：有父子关系

**Comment by Clouder0** [comment]
子级 Deck 用 "Parent::Children" 这样的名称。比如 `用户手册::开始上手`
